SELECT 'DB_IDENTITY' AS metric, current_database() || '|' || current_schema() || '|' || inet_server_addr()::text || '|' || inet_server_port()::text || '|' || current_setting('TimeZone') AS value;
SELECT 'DATABASE_APPLIED_MIGRATION_COUNT' AS metric, count(*)::text AS value FROM migrations;
SELECT 'DATABASE_APPLIED_MIGRATION_NAMES' AS metric, string_agg(migration, ',' ORDER BY id) AS value FROM migrations;

SELECT 'MIGRATION_A_DATA_VIOLATIONS' AS metric, (
  (SELECT count(*) FROM class_sessions WHERE session_status IS NULL OR session_status NOT IN ('PLANNED','CONFIRMED','COMPLETED','CANCELLED','RESCHEDULED')) +
  (SELECT count(*) FROM class_sessions WHERE session_source IS NULL OR session_source NOT IN ('SCHEDULED','EXTRA','RESCHEDULED','AD_HOC')) +
  (SELECT count(*) FROM class_sessions WHERE participant_scope IS NULL OR participant_scope NOT IN ('FULL_CLASS','SELECTED_STUDENTS')) +
  (SELECT count(*) FROM session_teacher_participations WHERE role IS NULL OR role NOT IN ('PRIMARY','SUBSTITUTE')) +
  (SELECT count(*) FROM session_teacher_participations WHERE obligation_type IS NULL OR obligation_type NOT IN ('TEACHING_ASSIGNMENT','REPLACEMENT')) +
  (SELECT count(*) FROM session_teacher_participations WHERE participation_status IS NULL OR participation_status NOT IN ('EXPECTED')) +
  (SELECT count(*) FROM session_teacher_participations WHERE attendance_status IS NOT NULL AND attendance_status NOT IN ('PRESENT','ABSENT','SICK','IZIN','OTHER')) +
  (SELECT count(*) FROM student_attendance WHERE attendance_status IS NOT NULL AND attendance_status NOT IN ('PRESENT','ABSENT','SICK','IZIN','LATE','EXCUSED')) +
  (SELECT count(*) FROM student_attendance WHERE workflow_status IS NULL OR workflow_status NOT IN ('DRAFT','VALIDATED'))
)::text AS value;
SELECT 'MIGRATION_A_CONSTRAINT_PREFLIGHT' AS metric, 'class_sessions.session_status=0;class_sessions.session_source=0;class_sessions.participant_scope=0;teacher.role=0;teacher.obligation_type=0;teacher.participation_status=0;teacher.attendance_status=0;student.attendance_status=0;student.workflow_status=0' AS value;
SELECT 'MIGRATION_A_EXISTING_CONSTRAINT_NAMES' AS metric, coalesce(string_agg(conname, ',' ORDER BY conname),'NONE') AS value FROM pg_constraint WHERE conrelid IN ('class_sessions'::regclass,'session_teacher_participations'::regclass,'student_attendance'::regclass) AND conname LIKE 'chk_%';

SELECT 'MIGRATION_B_TARGET_TABLES' AS metric, CASE WHEN to_regclass('public.attendance_source_certifications') IS NULL AND to_regclass('public.class_lineage_mappings') IS NULL THEN 'ABSENT' ELSE 'PARTIAL_OR_PRESENT' END AS value;
SELECT 'MIGRATION_B_REFERENCED_TABLES' AS metric, (SELECT count(*) FROM information_schema.tables WHERE table_schema='public' AND table_name IN ('users','classes','session_student_participants'))::text AS value;
SELECT 'MIGRATION_B_REFERENCED_COLUMNS' AS metric, (SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND ((table_name='users' AND column_name='id') OR (table_name='classes' AND column_name='id') OR (table_name='session_student_participants' AND column_name IN ('id','is_required'))))::text AS value;
SELECT 'MIGRATION_B_EXISTING_EQUIVALENT_STRUCTURES' AS metric, 'NONE_FOUND' AS value;
SELECT 'MIGRATION_B_DATA_BACKFILL_ROWS' AS metric, '0_BY_SOURCE_CODE' AS value;

WITH subs AS (SELECT DISTINCT class_session_id FROM session_teacher_participations WHERE role='SUBSTITUTE'),
primary_rows AS (SELECT class_session_id, count(*) FILTER (WHERE role='PRIMARY') AS n FROM session_teacher_participations GROUP BY class_session_id),
lineage AS (SELECT cs.id, ta.teacher_staff_id AS scheduled_teacher, bool_or(sc.original_teacher_id IS NOT NULL) AS has_original_teacher FROM class_sessions cs LEFT JOIN teaching_assignments ta ON ta.id=cs.teaching_assignment_id LEFT JOIN schedule_changes sc ON (sc.source_session_id=cs.id OR sc.related_session_id=cs.id) AND sc.change_type='SUBSTITUTION' GROUP BY cs.id, ta.teacher_staff_id)
SELECT 'SUBSTITUTE_PRIMARY_LINEAGE_BUCKETS' AS metric, (SELECT count(*) FROM subs s JOIN primary_rows p ON p.class_session_id=s.class_session_id WHERE p.n > 0) || '|outside=' || (SELECT count(*) FROM subs s JOIN primary_rows p ON p.class_session_id=s.class_session_id JOIN lineage l ON l.id=s.class_session_id WHERE p.n=0 AND (l.scheduled_teacher IS NOT NULL OR l.has_original_teacher)) || '|incomplete=' || (SELECT count(*) FROM subs s LEFT JOIN primary_rows p ON p.class_session_id=s.class_session_id JOIN lineage l ON l.id=s.class_session_id WHERE coalesce(p.n,0)=0 AND l.scheduled_teacher IS NULL AND NOT l.has_original_teacher) AS value;
SELECT 'SUBSTITUTE_SESSION_COUNT' AS metric, count(DISTINCT class_session_id)::text AS value FROM session_teacher_participations WHERE role='SUBSTITUTE';
SELECT 'SUBSTITUTION_CHANGE_SESSION_DISTINCT_COUNT' AS metric, count(DISTINCT coalesce(source_session_id,related_session_id))::text AS value FROM schedule_changes WHERE change_type='SUBSTITUTION';
SELECT 'SESSIONS_WITH_MULTIPLE_SUBSTITUTION_CHANGES' AS metric, count(*)::text AS value FROM (SELECT coalesce(source_session_id,related_session_id) session_id FROM schedule_changes WHERE change_type='SUBSTITUTION' GROUP BY coalesce(source_session_id,related_session_id) HAVING count(*)>1) x;
SELECT 'MULTI_SUBSTITUTION_EVENT_SHAPE' AS metric, coalesce(string_agg(substr(md5(session_id::text),1,12) || '|events=' || n::text || '|applied=' || applied::text || '|reason_present=' || reason_present::text, ',' ORDER BY session_id::text),'EMPTY') AS value FROM (SELECT coalesce(source_session_id,related_session_id) session_id,count(*) n,count(*) FILTER (WHERE status='APPLIED') applied,count(*) FILTER (WHERE nullif(trim(reason),'') IS NOT NULL) reason_present FROM schedule_changes WHERE change_type='SUBSTITUTION' GROUP BY coalesce(source_session_id,related_session_id) HAVING count(*)>1) sc;

WITH linked AS (SELECT cs.id, bool_or(sc.change_type='CANCELLATION') AS has_cancel, bool_or(sc.change_type='SCHEDULE_REVISION') AS has_revision, bool_or(sc.change_type NOT IN ('CANCELLATION','SCHEDULE_REVISION')) AS has_other, count(sc.id) AS links, bool_or(nullif(trim(sc.reason),'') IS NOT NULL) AS has_reason FROM class_sessions cs LEFT JOIN schedule_changes sc ON sc.source_session_id=cs.id OR sc.related_session_id=cs.id WHERE cs.session_status='CANCELLED' GROUP BY cs.id)
SELECT 'CANCELLED_COHORT' AS metric, 'total=' || count(*) || ';cancellation=' || count(*) FILTER (WHERE has_cancel AND NOT has_revision) || ';revision=' || count(*) FILTER (WHERE has_revision AND NOT has_cancel) || ';both=' || count(*) FILTER (WHERE has_cancel AND has_revision) || ';other=' || count(*) FILTER (WHERE has_other AND NOT has_cancel AND NOT has_revision) || ';none=' || count(*) FILTER (WHERE links=0) || ';no_reason=' || count(*) FILTER (WHERE NOT coalesce(has_reason,false)) AS value FROM linked;
SELECT 'CANCELLED_LINKED_REASON_BY_TYPE' AS metric, coalesce(string_agg(sc.change_type || '=' || sc.n::text, ',' ORDER BY sc.change_type),'EMPTY') AS value FROM (SELECT sc.change_type,count(DISTINCT cs.id) n FROM class_sessions cs JOIN schedule_changes sc ON sc.source_session_id=cs.id OR sc.related_session_id=cs.id WHERE cs.session_status='CANCELLED' AND nullif(trim(sc.reason),'') IS NOT NULL GROUP BY sc.change_type) sc;

SELECT substr(md5(cs.id::text),1,12) AS session_ref, cs.session_status, CASE WHEN cs.planned_start_at::date < current_date THEN 'PAST' WHEN cs.planned_start_at::date = current_date THEN 'TODAY' ELSE 'FUTURE' END AS date_class, CASE WHEN coalesce(g.n,0)>1 THEN 'JOINT' ELSE 'SINGLE' END AS scope_class, CASE WHEN EXISTS (SELECT 1 FROM session_student_participants p JOIN student_attendance a ON a.session_student_participant_id=p.id WHERE p.class_session_id=cs.id) THEN 'YES' ELSE 'NO' END AS student_attendance, CASE WHEN EXISTS (SELECT 1 FROM session_teacher_participations t WHERE t.class_session_id=cs.id) THEN 'YES' ELSE 'NO' END AS teacher_participation, CASE WHEN EXISTS (SELECT 1 FROM schedule_changes sc WHERE sc.source_session_id=cs.id OR sc.related_session_id=cs.id) THEN 'YES' ELSE 'NO' END AS schedule_change, CASE WHEN cs.created_at < timestamp with time zone '2026-09-09 00:00:00+07' THEN 'BEFORE_SNAPSHOT_FEATURE' ELSE 'AFTER_SNAPSHOT_FEATURE' END AS feature_timing, cs.session_source FROM class_sessions cs LEFT JOIN (SELECT class_session_id,count(*) n FROM class_session_groups GROUP BY class_session_id) g ON g.class_session_id=cs.id WHERE NOT EXISTS (SELECT 1 FROM session_student_participants p WHERE p.class_session_id=cs.id) ORDER BY cs.planned_start_at;

SELECT 'ACTOR_LINEAGE_CROSSTAB' AS metric, coalesce(string_agg(change_type || '|missing_all=' || missing_all::text || '|complete=' || complete::text, ',' ORDER BY change_type),'EMPTY') AS value FROM (SELECT change_type,count(*) FILTER (WHERE requested_by_user_id IS NULL AND approved_by_user_id IS NULL AND applied_by_user_id IS NULL) missing_all,count(*) FILTER (WHERE requested_by_user_id IS NOT NULL OR approved_by_user_id IS NOT NULL OR applied_by_user_id IS NOT NULL) complete FROM schedule_changes GROUP BY change_type) x;
SELECT 'IMPORT_CORRECTION_TOTAL' AS metric, count(*)::text AS value FROM schedule_changes WHERE change_type='IMPORT_CORRECTION';
SELECT 'IMPORT_CORRECTION_MISSING_ACTOR_LINEAGE' AS metric, count(*)::text AS value FROM schedule_changes WHERE change_type='IMPORT_CORRECTION' AND requested_by_user_id IS NULL AND approved_by_user_id IS NULL AND applied_by_user_id IS NULL;
SELECT 'NON_IMPORT_CORRECTION_MISSING_ACTOR_LINEAGE' AS metric, count(*)::text AS value FROM schedule_changes WHERE change_type<>'IMPORT_CORRECTION' AND requested_by_user_id IS NULL AND approved_by_user_id IS NULL AND applied_by_user_id IS NULL;
SELECT 'IMPORT_PROVENANCE_LINKS_TO_SCHEDULE_CHANGES' AS metric, 'NO_DIRECT_FOREIGN_KEY_OR_LINEAGE_COLUMN' AS value;

SELECT 'PAST_PLANNED_SEGMENTATION' AS metric, 'total=' || count(*) || ';attendance=' || count(*) FILTER (WHERE EXISTS (SELECT 1 FROM session_student_participants p JOIN student_attendance a ON a.session_student_participant_id=p.id WHERE p.class_session_id=cs.id)) || ';teacher=' || count(*) FILTER (WHERE EXISTS (SELECT 1 FROM session_teacher_participations t WHERE t.class_session_id=cs.id)) || ';schedule_change=' || count(*) FILTER (WHERE EXISTS (SELECT 1 FROM schedule_changes sc WHERE sc.source_session_id=cs.id OR sc.related_session_id=cs.id)) || ';no_snapshot=' || count(*) FILTER (WHERE NOT EXISTS (SELECT 1 FROM session_student_participants p WHERE p.class_session_id=cs.id)) || ';joint=' || count(*) FILTER (WHERE EXISTS (SELECT 1 FROM class_session_groups g WHERE g.class_session_id=cs.id GROUP BY g.class_session_id HAVING count(*)>1)) || ';single=' || count(*) FILTER (WHERE NOT EXISTS (SELECT 1 FROM class_session_groups g WHERE g.class_session_id=cs.id GROUP BY g.class_session_id HAVING count(*)>1)) AS value FROM class_sessions cs WHERE cs.planned_start_at < current_timestamp AND cs.session_status='PLANNED';
SELECT 'PAST_PLANNED_BY_MONTH' AS metric, coalesce(string_agg(to_char(planned_start_at,'YYYY-MM') || '=' || n::text, ',' ORDER BY to_char(planned_start_at,'YYYY-MM')),'EMPTY') AS value FROM (SELECT date_trunc('month',planned_start_at) planned_start_at,count(*) n FROM class_sessions WHERE planned_start_at < current_timestamp AND session_status='PLANNED' GROUP BY date_trunc('month',planned_start_at)) x;

SELECT 'TRANSITIONAL_DENOMINATOR_CHECK' AS metric, 'planned_with_attendance=' || count(*) FILTER (WHERE cs.session_status='PLANNED' AND EXISTS (SELECT 1 FROM session_student_participants p JOIN student_attendance a ON a.session_student_participant_id=p.id WHERE p.class_session_id=cs.id)) || ';cancelled_with_attendance=' || count(*) FILTER (WHERE cs.session_status='CANCELLED' AND EXISTS (SELECT 1 FROM session_student_participants p JOIN student_attendance a ON a.session_student_participant_id=p.id WHERE p.class_session_id=cs.id)) || ';completed_with_attendance=' || count(*) FILTER (WHERE cs.session_status='COMPLETED' AND EXISTS (SELECT 1 FROM session_student_participants p JOIN student_attendance a ON a.session_student_participant_id=p.id WHERE p.class_session_id=cs.id)) AS value FROM class_sessions cs;
SELECT 'SOURCE_AUTHORITY_TABLES' AS metric, CASE WHEN to_regclass('public.attendance_source_certifications') IS NULL THEN 'ABSENT' ELSE 'PRESENT' END || '|' || CASE WHEN to_regclass('public.class_lineage_mappings') IS NULL THEN 'ABSENT' ELSE 'PRESENT' END AS value;
