<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Master Guru</title><style>@include('academic.partials.sidebar-styles')</style></head>
<body><div class="waka-shell">@include('academic.partials.sidebar', ['activeMenu' => 'staff'])<main class="waka-content staff-list"><header class="waka-topbar"><div><p class="eyebrow">Data induk</p><h1>Master Guru/Staf</h1><p class="muted">Kelola identitas guru dan staf akademik.</p></div></header>
    <section class="card"><p class="eyebrow">Data induk</p><div class="actions"><div><h1>Master Guru/Staf</h1><p class="muted">Tambah identitas guru melalui Waka Akademik.</p></div><a class="button" href="{{ route('admin.academic.staff.create') }}">Tambah guru/staf</a></div><p class="notice" style="margin:1rem 0 0">Menampilkan {{ $staff->total() }} guru/staf resmi. {{ $pilotStaffCount }} data guru/staf pilot lama tetap tersimpan sebagai histori dan tidak dicampur dalam daftar operasional.</p></section>
    @if (session('status'))<p class="notice">{{ session('status') }}</p>@endif
    <section class="card" style="padding:1rem 1.2rem;background:#f3faf6"><div class="actions"><div><strong style="color:#17352b">Langkah berikutnya</strong><p class="muted" style="margin:.25rem 0 0">Guru yang aktif dapat langsung dipilih saat membuat penugasan mengajar.</p></div><div style="display:flex;gap:.55rem;flex-wrap:wrap"><a class="button" href="{{ route('admin.academic.teaching-assignments.create') }}">Tambah penugasan</a><a class="button" href="{{ route('admin.academic.schedules.index') }}">Buka jadwal</a></div></div></section>
    <section class="card"><p class="muted" style="margin:0 0 .6rem">Pada layar kecil, geser tabel ke kiri/kanan untuk melihat semua kolom.</p><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Nama</th><th>Mulai aktif</th><th>Status</th><th>Aksi</th></tr></thead><tbody>
    @forelse ($staff as $person)<tr><td>{{ $person->staff_code }}</td><td>{{ $person->full_name }}</td><td>{{ $person->active_from?->format('d M Y') ?? '—' }}</td><td>{{ $person->record_status === 'ACTIVE' ? 'Aktif' : 'Tidak aktif' }}</td><td><a href="{{ route('admin.academic.staff.edit', $person) }}">Edit</a></td></tr>@empty<tr><td colspan="5" class="muted">Belum ada guru/staf.</td></tr>@endforelse
    </tbody></table></div>{{ $staff->links() }}</section>
</main></div></body></html>
