<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Edit Jadwal</title>
    <style>
        @include('academic.partials.sidebar-styles')
        .schedule-card{max-width:72rem}.schedule-meta{display:flex;gap:.6rem;flex-wrap:wrap;margin:1rem 0;padding:.85rem 1rem;background:#f1f8f4;border:1px solid #d4e8dc;border-radius:.7rem;color:#176b4d}.schedule-meta span{color:#61776d}.schedule-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:0 1rem}.schedule-form>label{margin-top:0;margin-bottom:1rem}.schedule-form fieldset{grid-column:1/-1;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:.5rem;margin:0 0 1rem;padding:1rem;border:1px solid #d4e8dc;border-radius:.7rem;background:#f8fcfa}.schedule-form legend{grid-column:1/-1;color:#315447;font-weight:700}.schedule-form fieldset label{display:flex;align-items:center;gap:.4rem;margin:0;padding:.55rem;border:1px solid #d4e8dc;border-radius:.5rem;background:#fff}.schedule-form fieldset input{width:auto;margin:0}.schedule-form .wide{grid-column:1/-1}.archive-form{margin-top:1rem;padding-top:1rem;border-top:1px solid #dce8e1}.archive-form label{margin-top:0}.archive-form textarea{min-height:5rem;resize:vertical}.archive-form button{margin-top:.7rem}.form-actions{display:flex;gap:.75rem;flex-wrap:wrap;align-items:center}.danger{background:#b44e24}.danger:hover{background:#963d1e}@media(max-width:680px){.schedule-form{grid-template-columns:1fr}.schedule-form fieldset{grid-template-columns:repeat(2,minmax(0,1fr))}}
    </style>
</head>
<body><div class="waka-shell">
    @include('academic.partials.sidebar', ['activeMenu' => 'schedules'])
    <main class="waka-content"><header class="waka-topbar"><div><p class="eyebrow">Operasional akademik</p><h1>{{ $schedule->sessions()->exists() ? 'Revisi Jadwal' : 'Edit Jadwal' }}</h1><p class="muted">Perubahan jadwal dicatat tanpa menghapus histori sesi.</p></div></header>
        <section class="card schedule-card"><p><a class="back" href="{{ route('admin.academic.schedules.index') }}">Kembali ke data jadwal</a></p><p class="schedule-meta"><strong>{{ $schedule->teachingAssignment->assignment_code }}</strong><span>@uiLabel($schedule->teachingAssignment->academicClass->display_name) · @uiLabel($schedule->teachingAssignment->subject->subject_name)</span></p><p class="muted">{{ $schedule->sessions()->exists() ? 'Sesi lama tetap menjadi histori. Revisi ini membuat aturan baru mulai tanggal yang dipilih.' : 'Jadwal belum memiliki sesi dan dapat diedit langsung.' }}</p>
            @if ($errors->any())<div class="error"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
            <form class="schedule-form" method="post" action="{{ route('admin.academic.schedules.update', $schedule) }}">@csrf @method('PUT')
                <label>Hari<select name="weekday" required>@foreach ([1=>'Senin',2=>'Selasa',3=>'Rabu',4=>'Kamis',5=>'Jumat',6=>'Sabtu',7=>'Minggu'] as $day=>$label)<option value="{{ $day }}" @selected((string) old('weekday',$schedule->weekday)===(string)$day)>{{ $label }}</option>@endforeach</select></label>
                <label>Mulai<input type="time" name="start_time" value="{{ old('start_time',substr($schedule->start_time,0,5)) }}" required></label>
                <label>Selesai<input type="time" name="end_time" value="{{ old('end_time',substr($schedule->end_time,0,5)) }}" required></label>
                <label>Pengulangan<select name="recurrence_type" required><option value="EVERY_WEEK" @selected(old('recurrence_type',$schedule->recurrence_type)==='EVERY_WEEK')>Setiap minggu</option><option value="ODD_WEEK" @selected(old('recurrence_type',$schedule->recurrence_type)==='ODD_WEEK')>Minggu ganjil</option><option value="EVEN_WEEK" @selected(old('recurrence_type',$schedule->recurrence_type)==='EVEN_WEEK')>Minggu genap</option><option value="WEEK_OF_MONTH" @selected(old('recurrence_type',$schedule->recurrence_type)==='WEEK_OF_MONTH')>Minggu tertentu dalam bulan</option></select></label>
                @if ($schedule->sessions()->exists())<label>Guru pengajar revisi<select name="teacher_staff_id" required><option value="">Pilih guru</option>@foreach ($teachers as $teacher)<option value="{{ $teacher->id }}" @selected((string)old('teacher_staff_id',$schedule->teachingAssignment->teacher_staff_id)===(string)$teacher->id)>{{ $teacher->full_name }}</option>@endforeach</select></label><p class="muted">Guru lama tetap tercatat pada sesi historis. Pilihan ini berlaku untuk sesi baru mulai tanggal revisi.</p><label>Mata pelajaran revisi<select name="subject_id" required><option value="">Pilih mata pelajaran</option>@foreach ($subjects as $subject)<option value="{{ $subject->id }}" @selected((string)old('subject_id',$schedule->teachingAssignment->subject_id)===(string)$subject->id)>@uiLabel($subject->subject_name)</option>@endforeach</select></label>@endif
                <fieldset><legend>Nomor minggu dalam bulan</legend>@foreach (range(1,5) as $week)<label><input type="checkbox" name="week_numbers[]" value="{{ $week }}" @checked(in_array($week,old('week_numbers',$schedule->weekNumbers->pluck('week_no')->all())))> Minggu ke-{{ $week }}</label>@endforeach</fieldset>
                <label>{{ $schedule->sessions()->exists() ? 'Berlaku mulai revisi' : 'Berlaku mulai' }}<input type="text" name="{{ $schedule->sessions()->exists() ? 'revision_from' : 'effective_from' }}" value="{{ old($schedule->sessions()->exists()?'revision_from':'effective_from',$schedule->effective_from->format('d/m/Y')) }}" placeholder="dd/mm/yyyy" inputmode="numeric" autocomplete="off" required></label>
                <label>Berlaku sampai<input type="text" name="effective_until" value="{{ old('effective_until',$schedule->effective_until?->format('d/m/Y')) }}" placeholder="dd/mm/yyyy" inputmode="numeric" autocomplete="off" required></label>
                @if ($schedule->sessions()->exists())<label class="wide">Alasan revisi<textarea name="revision_reason" required>{{ old('revision_reason','Penyesuaian awal tahun pelajaran') }}</textarea></label>@endif
                <div class="form-actions wide"><button class="button" type="submit">Simpan perubahan</button><a class="button secondary" href="{{ route('admin.academic.schedules.index') }}">Batal</a></div>
            </form>
            @if (!$schedule->sessions()->exists())<form method="post" action="{{ route('admin.academic.schedules.destroy',$schedule) }}" onsubmit="return confirm('Hapus jadwal ini? Tindakan ini tidak dapat dibatalkan.');">@csrf @method('DELETE')<button class="button danger" type="submit">Hapus jadwal</button></form>@else<p class="muted">Jadwal ini memiliki sesi; gunakan Revisi Jadwal agar histori tetap aman.</p><form class="archive-form" method="post" action="{{ route('admin.academic.schedules.archive',$schedule) }}" onsubmit="return confirm('Arsipkan jadwal dan batalkan semua sesi kosong?');">@csrf<label>Alasan arsip<textarea name="archive_reason" required>Jadwal dihentikan dan sesi kosong dibatalkan.</textarea></label><button class="button danger" type="submit">Arsipkan & batalkan sesi kosong</button></form>@endif
        </section>
    </main>
</div></body></html>
