<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tingkat & Wali Kelas</title><style>@include('admin.partials.styles') .form-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(12rem,1fr));gap:.8rem}.table-wrap{overflow:auto}</style></head>
<body><main><header class="topbar"><a class="brand" href="{{ route('admin.academic.dashboard') }}">SISTEM IMTAQ <small>Waka Akademik</small></a><nav class="nav"><a href="{{ route('admin.academic.dashboard') }}">Ringkasan</a><a href="{{ route('admin.academic.classes.index') }}">Kelas</a><a class="active" href="{{ route('admin.academic.structure.index') }}">Tingkat & Wali Kelas</a><a href="{{ route('admin.academic.staff.index') }}">Guru/Staf</a><a href="{{ route('admin.academic.schedules.index') }}">Jadwal</a></nav></header>
<section class="card"><p class="eyebrow">Data induk akademik</p><h1>Tingkat & Wali Kelas</h1><p class="muted">Siapkan tingkat pendidikan dan tetapkan Wali Kelas dari Dashboard Waka Akademik.</p>@if ($currentAcademicYear)<p class="notice" style="margin:1rem 0 0">Daftar kelas menggunakan kelas resmi {{ $currentAcademicYear->display_name }}. Data pilot lama tetap tersimpan sebagai histori.</p>@endif</section>
@if (session('status'))<p class="notice">{{ session('status') }}</p>@endif @if ($errors->any())<div class="error"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="card"><h2>Tambah tingkat</h2><form method="post" action="{{ route('admin.academic.structure.grade-levels.store') }}"><div class="form-grid">@csrf<label>Unit organisasi<select name="organizational_unit_id" required><option value="">Pilih</option>@foreach ($units as $unit)<option value="{{ $unit->id }}">@uiLabel($unit->unit_name)</option>@endforeach</select></label><label>Kode tingkat<input name="level_code" placeholder="1" required></label><label>Nama tingkat<input name="display_name" placeholder="Tingkat 1" required></label><label>Urutan<input type="number" name="sequence_no" min="1" required></label></div><button class="button" type="submit">Simpan tingkat</button></form></section>
<section class="card"><h2>Tambah Wali Kelas</h2><p class="muted">Pilihan hanya menampilkan guru/staf resmi. Penetapan pilot lama tetap tersimpan sebagai histori.</p><form method="post" action="{{ route('admin.academic.structure.homerooms.store') }}"><div class="form-grid">@csrf<label>Kelas<select name="class_id" required><option value="">Pilih</option>@foreach ($classes as $class)<option value="{{ $class->id }}">@uiLabel($class->display_name)</option>@endforeach</select></label><label>Wali Kelas<select name="staff_id" required><option value="">Pilih</option>@foreach ($staff as $person)<option value="{{ $person->id }}">{{ $person->full_name }}</option>@endforeach</select></label><label>Mulai bertugas<input type="date" name="effective_from" required></label><label>Selesai bertugas<input type="date" name="effective_until"></label><label>Alasan penetapan<input name="reason" value="MASTER-DATA-ADMIN" required></label></div><button class="button" type="submit">Tetapkan Wali Kelas</button></form></section>
<section class="card"><h2>Daftar tingkat</h2><div class="table-wrap"><table><thead><tr><th>Kode</th><th>Nama</th><th>Unit</th><th>Urutan</th></tr></thead><tbody>@forelse ($gradeLevels as $level)<tr><td>{{ $level->level_code }}</td><td>@uiLabel($level->display_name)</td><td>@uiLabel($level->organizationalUnit->unit_name)</td><td>{{ $level->sequence_no }}</td></tr>@empty<tr><td colspan="4" class="muted">Belum ada tingkat.</td></tr>@endforelse</tbody></table></div></section>
<section class="card"><h2>Wali Kelas aktif</h2><div class="table-wrap"><table><thead><tr><th>Kelas</th><th>Wali Kelas</th><th>Mulai</th><th>Selesai</th><th>Aksi</th></tr></thead><tbody>@forelse ($classes as $class) @foreach ($class->homeroomAssignments->where('status','ACTIVE') as $assignment)<tr><td>@uiLabel($class->display_name)</td><td>{{ $assignment->staff->full_name }}</td><td>{{ $assignment->effective_from->format('d-m-Y') }}</td><td>{{ $assignment->effective_until?->format('d-m-Y') ?? 'Masih aktif' }}</td><td><a href="{{ route('admin.academic.structure.homerooms.edit', $assignment) }}">Edit</a></td></tr>@endforeach @empty<tr><td colspan="5" class="muted">Belum ada penetapan.</td></tr>@endforelse</tbody></table></div></section>
</main><form method="POST" action="{{ route('logout') }}" style="max-width:78rem;margin:0 auto 1rem;text-align:right">@csrf<button class="button" type="submit">Keluar</button></form></body></html>
