<!doctype html>
<html lang="id">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kelola User</title>
<style>@include('academic.partials.sidebar-styles')body{background:#f3f8f5;color:#173d33}.page{display:grid;gap:1rem;max-width:70rem}.card{background:#fff;border:1px solid #cfe4d9;border-radius:1rem;padding:clamp(1rem,2.5vw,1.7rem)}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(18rem,1fr));gap:1rem}.field{display:grid;gap:.35rem;margin:.8rem 0}.field input,.field select,.field textarea{min-height:2.6rem;padding:.55rem;border:1px solid #b9dac7;border-radius:.6rem;font:inherit}.button{min-height:2.6rem;padding:.55rem .9rem;border:0;border-radius:.6rem;background:#176b4d;color:#fff;font-weight:800}.danger{background:#a93e4d}.muted{color:#5b756c}.eyebrow{color:#176b4d;font-size:.75rem;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.feature{display:grid;grid-template-columns:1fr 10rem;gap:1rem;align-items:center;padding:.7rem 0;border-bottom:1px solid #dcebe2}.role{padding:.7rem;border:1px solid #dcebe2;border-radius:.6rem;margin:.5rem 0;display:flex;justify-content:space-between;gap:.8rem;align-items:center}.role form{margin:0}@media(max-width:680px){.feature{grid-template-columns:1fr}.button{width:100%}.role{align-items:flex-start;flex-direction:column}}</style>
</head>
<body><div class="waka-shell">@include('academic.partials.sidebar',['activeMenu'=>'users'])
<main class="waka-content"><div class="page">
<header><p class="eyebrow">User &amp; Akses</p><h1>{{ $managedUser->name }}</h1><p class="muted">{{ $managedUser->email }} · ID {{ $managedUser->id }}</p></header>
@if(session('status'))<p class="card" role="status">{{ session('status') }}</p>@endif
@if($errors->any())<p class="card" role="alert">{{ $errors->first() }}</p>@endif
<section class="card"><h2>Akun &amp; Staff</h2>@if($showHelpText)<p class="muted">Akun disabled ditolak pada login dan sesi aktif. Password sementara wajib diganti saat login berikutnya.</p>@endif
<form method="post" action="{{ route('admin.system.users.account.update',$managedUser) }}">@csrf @method('PUT')<div class="grid">
<div class="field"><label for="name">Nama</label><input id="name" name="name" value="{{ $managedUser->name }}" required></div>
<div class="field"><label for="email">Email</label><input id="email" type="email" name="email" value="{{ $managedUser->email }}" required></div>
<div class="field"><label for="status">Status akun</label><select id="status" name="status"><option value="ACTIVE" @selected(($managedUser->status ?? 'ACTIVE') === 'ACTIVE')>ACTIVE</option><option value="DISABLED" @selected($managedUser->status === 'DISABLED')>DISABLED</option></select></div>
<div class="field"><label for="staff_id">Staff terkait</label><select id="staff_id" name="staff_id"><option value="">Belum ditautkan</option>@foreach($staff as $person)<option value="{{ $person->id }}" @selected($managedUser->staffLink?->staff_id === $person->id)>{{ $person->full_name }} · {{ $person->staff_code }}</option>@endforeach</select></div></div>
<div class="field"><label for="password">Password sementara baru (opsional)</label><input id="password" type="password" name="password" minlength="12" autocomplete="new-password"><small class="muted">Tidak ditampilkan, disimpan plaintext, atau dimasukkan ke audit.</small></div><button class="button" type="submit">Simpan akun</button></form></section>
<section class="card"><h2>Role &amp; Scope</h2>
@foreach($managedUser->roleAssignments as $assignment)<div class="role"><div><strong>{{ $assignment->role->name }}</strong><span class="muted"> · {{ $assignment->scope_type }}{{ $assignment->scope_key ? ' / '.$assignment->scope_key : '' }} · {{ $assignment->effective_from?->format('Y-m-d') ?? 'tanpa mulai' }} — {{ $assignment->effective_until?->format('Y-m-d') ?? 'aktif' }}</span></div>@if(!$assignment->effective_until || $assignment->effective_until->isFuture())<form method="post" action="{{ route('admin.system.users.roles.revoke',[$managedUser,$assignment]) }}">@csrf @method('DELETE')<button class="button danger" type="submit">Cabut assignment</button></form>@endif</div>@endforeach
<form method="post" action="{{ route('admin.system.users.roles.update',$managedUser) }}">@csrf<div class="grid"><div class="field"><label for="role_id">Tambah role</label><select id="role_id" name="role_id" required>@foreach($roles as $role)<option value="{{ $role->id }}">{{ $role->name }}</option>@endforeach</select></div><div class="field"><label for="role_scope_type">Scope type</label><select id="role_scope_type" name="scope_type" required>@foreach(['SELF','ASSIGNED_SESSION','ASSIGNED_CLASS','HOMEROOM_CLASS','DEPARTMENT','UNIT','INSTITUTION'] as $scope)<option value="{{ $scope }}" @selected($scope==='INSTITUTION')>{{ $scope }}</option>@endforeach</select></div><div class="field"><label for="role_scope_key">Scope key</label><input id="role_scope_key" name="scope_key" placeholder="ID canonical resource bila diperlukan"></div><div class="field"><label for="effective_from">Mulai berlaku</label><input id="effective_from" type="date" name="effective_from"></div><div class="field"><label for="effective_until">Berakhir</label><input id="effective_until" type="date" name="effective_until"></div></div><button class="button" type="submit">Tambahkan assignment</button></form></section>
<section class="card"><h2>Akses Fitur</h2>@if($showHelpText)<p class="muted">Override hanya mengatur feature gate. Override tidak pernah menggantikan permission atau scope backend. Setiap perubahan menyimpan alasan dan versi.</p>@endif
<form method="post" action="{{ route('admin.system.users.features.update',$managedUser) }}">@csrf @method('PUT')@foreach($features->groupBy('module') as $module => $moduleFeatures)<h3>{{ $module }}</h3>@foreach($moduleFeatures as $feature)@php($override=$managedUser->featureOverrides->firstWhere('feature_id',$feature->id))@php($state=$override?->state ?? 'INHERIT')@php($result=$resolver->resolve($managedUser,$feature->code))<div class="feature"><div><strong>{{ $feature->name }}</strong><br><small class="muted">{{ $feature->code }} · Efektif: {{ $result['effective_enabled'] ? 'diizinkan' : 'ditolak ('.$result['denial_reason'].')' }} · v{{ $override?->version_no ?? 0 }}</small><div class="field"><label for="reason-{{ $feature->id }}">Alasan override</label><input id="reason-{{ $feature->id }}" name="feature_reasons[{{ $feature->id }}]" value="{{ $override?->reason }}" maxlength="1000"></div></div><select name="features[{{ $feature->id }}]" aria-label="Override {{ $feature->name }}"><option value="INHERIT" @selected($state==='INHERIT')>INHERIT</option><option value="ENABLED" @selected($state==='ENABLED')>ENABLED</option><option value="DISABLED" @selected($state==='DISABLED')>DISABLED</option></select></div>@endforeach @endforeach<button class="button" type="submit">Simpan akses fitur</button></form></section>
<section class="card"><h2>Preferensi</h2>@if($showHelpText)<p class="muted">Preferensi hanya mengubah tampilan dan landing yang aman; tidak menambah authorization.</p>@endif
<form method="post" action="{{ route('admin.system.users.preferences.update',$managedUser) }}">@csrf @method('PUT')@php($prefs=$managedUser->preferences->keyBy('preference_key')->map(fn($p)=>$p->preference_value['value'] ?? null))<div class="grid"><div class="field"><label for="default_landing_page">Halaman awal</label><select id="default_landing_page" name="default_landing_page"><option value="academic.dashboard" @selected($prefs->get('default_landing_page')==='academic.dashboard')>Dashboard akademik</option><option value="admin.academic.dashboard" @selected($prefs->get('default_landing_page')==='admin.academic.dashboard')>Dashboard admin</option></select></div><div class="field"><label for="table_page_size">Jumlah baris tabel User &amp; Akses</label><select id="table_page_size" name="table_page_size"><option value="10" @selected((string)$prefs->get('table_page_size')==='10')>10</option><option value="25" @selected((string)$prefs->get('table_page_size')==='25' || !$prefs->has('table_page_size'))>25</option><option value="50" @selected((string)$prefs->get('table_page_size')==='50')>50</option></select></div></div><label><input type="checkbox" name="sidebar_compact" value="1" @checked($prefs->get('sidebar_compact') === true)> Sidebar ringkas</label><br><label><input type="checkbox" name="show_help_text" value="1" @checked($prefs->get('show_help_text') !== false)> Tampilkan bantuan</label><p><button class="button" type="submit">Simpan preferensi</button></p></form></section>
</div></main></div></body></html>
