@include('admin.partials.styles')
body{padding:0;background:#f4f8f6;color:#12372d}
.waka-shell{display:grid;grid-template-columns:4.4rem minmax(0,1fr);min-height:100vh}
.waka-sidebar{display:flex;flex-direction:column;background:linear-gradient(180deg,#07553f,#063d31);color:#ecfff5;padding:1.35rem .55rem;position:sticky;top:0;height:100vh;width:4.4rem;z-index:10;transition:width .2s ease,padding .2s ease;overflow:hidden}
.waka-sidebar:hover,.waka-sidebar:focus-within{width:14rem;padding-left:1rem;padding-right:1rem;box-shadow:10px 0 24px rgba(6,61,49,.16)}
.waka-brand{display:flex;gap:.65rem;align-items:center;justify-content:center;color:#fff;text-decoration:none;font-weight:800;font-size:1.05rem;letter-spacing:-.03em;padding:.25rem .45rem 1.8rem;white-space:nowrap}
.waka-brand small{display:block;color:#bde4d0;font-size:.62rem;letter-spacing:.08em;text-transform:uppercase;margin-top:.15rem}
.waka-mark{width:2.75rem;height:2.75rem;border-radius:.35rem;object-fit:contain;background:#fff;display:block;flex:none}
.waka-nav{display:grid;gap:.35rem}.waka-nav a{display:flex;align-items:center;gap:.65rem;color:#d1eee0;text-decoration:none;padding:.7rem .55rem;border-radius:.65rem;font-size:.8rem}.waka-nav a:hover,.waka-nav a.active{background:#f4fff8;color:#07553f;font-weight:800}.waka-nav .nav-icon{width:1.35rem;text-align:center;font-size:1.2rem;line-height:1.1;flex:none}
.waka-brand span:not(.waka-mark),.waka-nav a span:not(.nav-icon),.waka-sidebar-footer{display:none}.waka-sidebar:hover .waka-brand span:not(.waka-mark),.waka-sidebar:focus-within .waka-brand span:not(.waka-mark),.waka-sidebar:hover .waka-nav a span:not(.nav-icon),.waka-sidebar:focus-within .waka-nav a span:not(.nav-icon),.waka-sidebar:hover .waka-sidebar-footer,.waka-sidebar:focus-within .waka-sidebar-footer{display:block}.waka-sidebar:hover .waka-nav a,.waka-sidebar:focus-within .waka-nav a{justify-content:flex-start}
.waka-sidebar:hover .waka-brand,.waka-sidebar:focus-within .waka-brand{justify-content:flex-start;padding-left:.75rem}
.waka-sidebar-footer{margin-top:auto;border-top:1px solid rgba(255,255,255,.18);padding-top:1rem;color:#bde4d0;font-size:.72rem;line-height:1.45;white-space:nowrap}.waka-sidebar-account{display:flex;align-items:center;gap:.55rem;margin-bottom:.55rem}.waka-sidebar-account strong{display:block;color:#fff;font-size:.84rem}.waka-sidebar-avatar{width:1.85rem;height:1.85rem;border-radius:50%;display:grid;place-items:center;background:#ccebdc;color:#086b4f;font-size:.68rem;font-weight:900;flex:none}.waka-sidebar-footer small{display:block}.waka-sidebar-logout{width:100%;margin-top:.8rem;border:1px solid rgba(255,255,255,.3);border-radius:.5rem;background:rgba(255,255,255,.08);color:#fff;padding:.45rem .6rem;font:inherit;font-weight:800;text-align:left;cursor:pointer}.waka-sidebar-logout:hover,.waka-sidebar-logout:focus-visible{background:#f4fff8;color:#07553f}
.waka-content{min-width:0;padding:1.45rem 1.65rem 2.25rem}.waka-topbar{display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:1.35rem}.waka-user{display:flex;align-items:center;gap:.6rem;color:#6a8278;font-size:.82rem;white-space:nowrap}.waka-avatar{width:2.35rem;height:2.35rem;border-radius:50%;display:grid;place-items:center;background:#ccebdc;color:#086b4f;font-weight:900}.waka-logout{border:0;background:transparent;color:#086b4f;font:inherit;font-weight:800;cursor:pointer;margin-left:.3rem}
@media(max-width:1000px){.waka-sidebar:hover,.waka-sidebar:focus-within{padding-left:.7rem;padding-right:.7rem}}
@media(max-width:680px){.waka-shell{display:block}.waka-sidebar{position:fixed;left:0;top:0;width:4.4rem;height:100vh;padding:1rem .55rem;overflow:hidden}.waka-sidebar.is-expanded{width:12rem;padding-left:1rem;padding-right:1rem;box-shadow:10px 0 24px rgba(6,61,49,.16)}.waka-brand{padding:.2rem .45rem 1.4rem}.waka-sidebar .waka-brand span:not(.waka-mark),.waka-sidebar .waka-nav a span:not(.nav-icon),.waka-sidebar .waka-sidebar-footer{display:none}.waka-sidebar.is-expanded .waka-brand span:not(.waka-mark),.waka-sidebar.is-expanded .waka-nav a span:not(.nav-icon),.waka-sidebar.is-expanded .waka-sidebar-footer{display:block}.waka-sidebar.is-expanded .waka-nav a{justify-content:flex-start}.waka-sidebar.is-expanded .waka-brand{justify-content:flex-start;padding-left:1.75rem}.waka-nav{display:grid;gap:.35rem}.waka-nav a{justify-content:center;padding:.7rem .55rem}.waka-sidebar-footer{display:none}.waka-sidebar.is-expanded .waka-sidebar-footer{display:block}.waka-content{padding:.9rem;margin-left:4.4rem}.waka-topbar{align-items:flex-start}.waka-user{font-size:0}.waka-user .waka-logout{font-size:.78rem}}
@media(max-width:680px){.waka-sidebar.is-expanded .waka-brand{justify-content:flex-start;padding-left:.75rem}.waka-sidebar.is-expanded .waka-nav a{padding-left:.75rem;padding-right:.75rem}}
@media(max-width:680px){.waka-sidebar.is-expanded{width:14rem}}
.attendance-page .button-row>button{border:1px solid #0f5f42!important;border-radius:.7rem!important;padding:.65rem 1rem!important;background:linear-gradient(135deg,#19845f,#0f684a)!important;color:#fff!important;font:inherit;font-weight:800;line-height:1.2;box-shadow:0 5px 12px rgba(7,85,63,.16);transition:transform .15s ease,box-shadow .15s ease,filter .15s ease}.attendance-page .button-row>button:hover,.attendance-page .button-row>button:focus-visible{filter:brightness(1.06);transform:translateY(-1px);box-shadow:0 7px 16px rgba(7,85,63,.22)}.attendance-page .button-row>button.secondary{background:#e5f2eb!important;color:#176b4d!important;border-color:#b9dac7!important;box-shadow:none}.attendance-page .button-row>button.secondary:hover,.attendance-page .button-row>button.secondary:focus-visible{background:#d8eee2!important}
.staff-list table td:nth-child(4){color:#176b4d;font-weight:800}.staff-list table td:last-child a{display:inline-flex;padding:.45rem .7rem;border:1px solid #b9dac7;border-radius:.55rem;background:#edf8f1;color:#176b4d;text-decoration:none;font-weight:800;white-space:nowrap}.staff-list table td:last-child a:hover,.staff-list table td:last-child a:focus-visible{background:#dcefe3;transform:translateY(-1px)}
.class-table td:nth-child(5){color:#176b4d;font-weight:800}.class-table td:last-child a{display:inline-flex;align-items:center;justify-content:center;padding:.45rem .7rem;border:1px solid #b9dac7;border-radius:.55rem;background:#edf8f1;color:#176b4d;text-decoration:none;font-weight:800;white-space:nowrap;transition:background .15s ease,transform .15s ease}.class-table td:last-child a:hover,.class-table td:last-child a:focus-visible{background:#dcefe3;transform:translateY(-1px)}
.bulk-roster-submit button{display:inline-flex;align-items:center;gap:.5rem;border:1px solid #0f5f42!important;border-radius:.7rem!important;padding:.65rem 1rem!important;background:linear-gradient(135deg,#19845f,#0f684a)!important;color:#fff!important;font:inherit;font-weight:800;line-height:1.2;box-shadow:0 5px 12px rgba(7,85,63,.18);transition:transform .15s ease,box-shadow .15s ease,filter .15s ease}.bulk-roster-submit button::before{content:'+';display:grid;place-items:center;width:1.15rem;height:1.15rem;border:1px solid rgba(255,255,255,.7);border-radius:50%;font-size:.9rem;line-height:1}.bulk-roster-submit button:hover,.bulk-roster-submit button:focus-visible{filter:brightness(1.06);transform:translateY(-1px);box-shadow:0 7px 16px rgba(7,85,63,.24)}
