<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tambah Jadwal</title><style>@include('academic.partials.sidebar-styles') .schedule-form .assignment-advanced{grid-column:1/-1;margin:.2rem 0;padding:.8rem 1rem;border:1px solid #d6e6de;border-radius:.7rem;background:#f7fbf9}.assignment-advanced summary{cursor:pointer;color:#176b45;font-weight:800}.assignment-advanced label{margin-top:.7rem}.assignment-advanced .muted{margin:.45rem 0 0;font-size:.9rem}.setup-note{grid-column:1/-1;margin:-.3rem 0 .1rem;color:#5c776c;font-size:.92rem}</style></head>
<body><div class="waka-shell">@include('academic.partials.sidebar', ['activeMenu' => 'schedules'])<main class="waka-content"><section class="card" style="max-width:70rem"><p class="eyebrow">Operasional akademik</p><h1>Tambah Jadwal</h1><p><a class="back" href="{{ route('admin.academic.schedules.index') }}">Kembali ke data jadwal</a></p>
@if ($errors->any())<div class="error"><ul>@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="schedule-form" method="post" action="{{ route('admin.academic.schedules.store') }}">@csrf
<p class="setup-note">Pilih semester, kelas, mata pelajaran, dan guru. Sistem akan menyiapkan penugasan secara otomatis bila kombinasi ini belum tersedia.</p>
<label>Semester<select name="semester_id" @if($assignments->isEmpty()) required @endif><option value="">Pilih semester</option>@foreach ($semesters as $semester)<option value="{{ $semester->id }}" @selected(old('semester_id') === $semester->id)>Semester {{ ['I', 'II', 'III', 'IV'][$semester->sequence_no - 1] ?? $semester->sequence_no }} {{ $semester->academicYear?->year_code }}</option>@endforeach</select></label>
<label>Kelas<select name="class_id" @if($assignments->isEmpty()) required @endif><option value="">Pilih kelas</option>@foreach ($classes as $class)<option value="{{ $class->id }}" @selected(old('class_id') === $class->id)>{{ $class->display_name }}</option>@endforeach</select></label>
<label>Mata pelajaran<select name="subject_id" @if($assignments->isEmpty()) required @endif><option value="">Pilih mata pelajaran</option>@foreach ($subjects as $subject)<option value="{{ $subject->id }}" @selected(old('subject_id') === $subject->id)>@uiLabel($subject->subject_name)</option>@endforeach</select></label>
<label>Guru/Asatidzah<select name="teacher_staff_id" @if($assignments->isEmpty()) required @endif><option value="">Pilih guru</option>@foreach ($teachers as $teacher)<option value="{{ $teacher->id }}" @selected(old('teacher_staff_id') === $teacher->id)>{{ $teacher->full_name }}</option>@endforeach</select></label>
<details class="assignment-advanced"><summary>Gunakan penugasan tersimpan (opsional)</summary><label>Penugasan mengajar<select name="teaching_assignment_id"><option value="">Gunakan pilihan di atas</option>@foreach ($assignments as $assignment)<option value="{{ $assignment->id }}" title="Kode: {{ $assignment->assignment_code }}" @selected(old('teaching_assignment_id') === $assignment->id)>@uiLabel($assignment->academicClass->display_name) · @uiLabel($assignment->subject->subject_name) · {{ $assignment->teacher?->full_name ?? 'Guru belum ditentukan' }}</option>@endforeach</select></label><p class="muted">Belum ada kombinasi yang sesuai? <a href="{{ route('admin.academic.subjects.create') }}">Tambah mata pelajaran</a> · <a href="{{ route('admin.academic.staff.create') }}">Tambah guru</a> · <a href="{{ route('admin.academic.teaching-assignments.create') }}">Tambah penugasan</a></p></details>
<label>Hari<select name="weekday" required>@foreach ([1 => 'Senin', 2 => 'Selasa', 3 => 'Rabu', 4 => 'Kamis', 5 => 'Jumat', 6 => 'Sabtu', 7 => 'Minggu'] as $day => $label)<option value="{{ $day }}" @selected((string) old('weekday', '1') === (string) $day)>{{ $label }}</option>@endforeach</select></label>
<label>Mulai<input type="time" name="start_time" value="{{ old('start_time') }}" required></label>
<label>Selesai<input type="time" name="end_time" value="{{ old('end_time') }}" required></label>
<label>Pengulangan<select name="recurrence_type" required><option value="EVERY_WEEK">Setiap minggu</option><option value="ODD_WEEK">Minggu ganjil</option><option value="EVEN_WEEK">Minggu genap</option><option value="WEEK_OF_MONTH">Minggu tertentu dalam bulan</option></select></label>
<fieldset><legend>Nomor minggu dalam bulan (untuk pilihan tertentu)</legend>@foreach (range(1, 5) as $week)<label><input type="checkbox" name="week_numbers[]" value="{{ $week }}" @checked(in_array($week, old('week_numbers', [])))> Minggu ke-{{ $week }}</label>@endforeach</fieldset>
<label>Berlaku mulai<input lang="id" type="date" name="effective_from" value="{{ old('effective_from') }}" required></label>
<label>Berlaku sampai<input lang="id" type="date" name="effective_until" value="{{ old('effective_until') }}" required></label>
<button class="button" type="submit">Simpan jadwal dan buat sesi</button></form></section></main></div></body></html>
